### PR TITLE
WIP: Styled About page

### PR DESCRIPTION
**Pull request by TaylorAleseHarris**

### CODE REVIEW

**Review by williambeukelman — COMMENTED** [review]
Looks a lot better, mobile styles are a bit broken though.

**Comment by williambeukelman** [comment]
Fixed the styling and rebased.

**Review by williambeukelman — APPROVED** [review]
Looks fine on web and mobile and I don't see any conflicts with the code base.

**Comment by TaylorAleseHarris** [comment]
On my end the web styling is all squished now, I'm going to try to get it back where it was.

**Pull request merged**
